import 'dart:convert';
import 'dart:io';

final _escapePattern = RegExp(r'[\\^$.|?*+()\[\]{}]');
RegExp _setToPattern(Set<String> set) {
  final escaped = set.map(
    (s) => s.replaceAllMapped(_escapePattern, (match) => '\\${match.group(0)}'),
  );
  return RegExp('[${escaped.join('')}]');
}

final _defaultWhitespacePattern = RegExp(r'[\s]');
final _defaultPunctuationPattern = RegExp(r'[^\w]');

final class Definibus {
  final Set<String> words;
  final List<String> lines;

  const Definibus(this.words, this.lines);

  factory Definibus.fromLines(
    List<String> lines, {
    Pattern? punctuationPattern,
    Pattern? whitespacePattern,
  }) {
    assert(lines.isNotEmpty, "Lines must not be empty.");

    final words = Set<String>.from(lines
        .map(
          (l) => l
              .split(whitespacePattern ?? _defaultWhitespacePattern)
              .map((s) => s.toLowerCase()),
        )
        .map(
          (l) => l.where((c) =>
              c.isNotEmpty &&
              !c.contains(punctuationPattern ?? _defaultPunctuationPattern)),
        )
        .expand((split) => split));

    assert(words.isNotEmpty, "Words must not be empty.");

    return Definibus(words, lines);
  }

  static const defaultDefinibus =
      Definibus(_defaultDefinibusWords, _defaultDefinibusLines);

  factory Definibus.fromString(
    String str, {
    Set<String> lineDelimiters = const {'.', '?', '!'},
  }) {
    final lines = str.split(_setToPattern(lineDelimiters));
    return Definibus.fromLines(lines);
  }

  factory Definibus.fromFile(
    File file, {
    Encoding encoding = utf8,
    Set<String> lineDelimiters = const {'.', '?', '!'},
  }) {
    if (!file.existsSync()) {
      throw ArgumentError('Given file does not exist.');
    }

    final content = file.readAsStringSync(encoding: encoding);
    return Definibus.fromString(content, lineDelimiters: lineDelimiters);
  }
}

const _defaultDefinibusWords = {
  "pertinax",
  "non",
  "ero",
  "si",
  "mihi",
  "probabis",
  "quae",
  "libenter",
  "modo",
  "ista",
  "sis",
  "quam",
  "sed",
  "uti",
  "oratione",
  "perpetua",
  "malo",
  "interrogare",
  "aut",
  "ut",
  "tum",
  "dicere",
  "exorsus",
  "primum",
  "sic",
  "ipsi",
  "auctori",
  "huius",
  "disciplinae",
  "quid",
  "et",
  "quale",
  "sit",
  "de",
  "quo",
  "ignorare",
  "vos",
  "ratione",
  "via",
  "procedat",
  "quaerimus",
  "extremum",
  "ultimum",
  "quod",
  "omnium",
  "philosophorum",
  "sententia",
  "tale",
  "debet",
  "ad",
  "id",
  "omnia",
  "referri",
  "ipsum",
  "autem",
  "hoc",
  "epicurus",
  "in",
  "voluptate",
  "summum",
  "bonum",
  "esse",
  "summumque",
  "malum",
  "idque",
  "instituit",
  "docere",
  "omne",
  "simul",
  "atque",
  "natum",
  "voluptatem",
  "appetere",
  "eaque",
  "gaudere",
  "summo",
  "dolorem",
  "aspernari",
  "quantum",
  "a",
  "se",
  "facere",
  "nondum",
  "depravatum",
  "ipsa",
  "natura",
  "incorrupte",
  "integre",
  "itaque",
  "negat",
  "opus",
  "neque",
  "ob",
  "rem",
  "voluptas",
  "fugiendus",
  "dolor",
  "sentiri",
  "haec",
  "calere",
  "nivem",
  "dulce",
  "quorum",
  "nihil",
  "oportere",
  "exquisitis",
  "rationibus",
  "tantum",
  "satis",
  "interesse",
  "enim",
  "inter",
  "argumentum",
  "conclusionemque",
  "rationis",
  "mediocrem",
  "animadversionem",
  "altera",
  "occulta",
  "quaedam",
  "quasi",
  "involuta",
  "prompta",
  "aperta",
  "etenim",
  "quoniam",
  "detractis",
  "homine",
  "sensibus",
  "reliqui",
  "necesse",
  "naturam",
  "contra",
  "ea",
  "percipit",
  "petat",
  "fugiat",
  "praeter",
  "sunt",
  "quidam",
  "e",
  "qui",
  "subtilius",
  "velint",
  "tradere",
  "negent",
  "sensu",
  "animo",
  "etiam",
  "ac",
  "intellegi",
  "posse",
  "ipsam",
  "per",
  "expetendam",
  "aiunt",
  "hanc",
  "naturalem",
  "insitam",
  "animis",
  "nostris",
  "inesse",
  "alterum",
  "aspernandum",
  "alii",
  "quibus",
  "ego",
  "cum",
  "philosophis",
  "compluribus",
  "permulta",
  "cur",
  "nec",
  "bonis",
  "numeranda",
  "malis",
  "existimant",
  "nimium",
  "nos",
  "causae",
  "argumentandum",
  "accurate",
  "disserendum",
  "conquisitis",
  "dolore",
  "disputandum",
  "unde",
  "omnis",
  "iste",
  "natus",
  "error",
  "accusantium",
  "doloremque",
  "totam",
  "aperiam",
  "ab",
  "illo",
  "inventore",
  "veritatis",
  "architecto",
  "beatae",
  "vitae",
  "dicta",
  "nemo",
  "quia",
  "aspernatur",
  "odit",
  "consequuntur",
  "magni",
  "dolores",
  "sequi",
  "porro",
  "quisquam",
  "adipisci",
  "numquam",
  "eius",
  "modi",
  "tempora",
  "labore",
  "magnam",
  "aliquam",
  "quaerat",
  "minima",
  "quis",
  "nostrum",
  "exercitationem",
  "ullam",
  "corporis",
  "suscipit",
  "nisi",
  "aliquid",
  "ex",
  "commodi",
  "vel",
  "eum",
  "iure",
  "velit",
  "molestiae",
  "nulla",
  "at",
  "vero",
  "eos",
  "accusamus",
  "iusto",
  "odio",
  "dignissimos",
  "blanditiis",
  "praesentium",
  "voluptatum",
  "deleniti",
  "quos",
  "quas",
  "molestias",
  "excepturi",
  "obcaecati",
  "cupiditate",
  "similique",
  "officia",
  "deserunt",
  "mollitia",
  "est",
  "laborum",
  "dolorum",
  "harum",
  "quidem",
  "rerum",
  "facilis",
  "expedita",
  "nam",
  "libero",
  "soluta",
  "nobis",
  "eligendi",
  "cumque",
  "minus",
  "maxime",
  "assumenda",
  "temporibus",
  "quibusdam",
  "officiis",
  "debitis",
  "necessitatibus",
  "saepe",
  "voluptates",
  "repudiandae",
  "sint",
  "earum",
  "hic",
  "tenetur",
  "sapiente",
  "reiciendis",
  "voluptatibus",
  "maiores",
  "alias",
  "consequatur",
  "perferendis",
  "doloribus",
  "asperiores"
};

const _defaultDefinibusLines = [
  "Certe, inquam, pertinax non ero tibique, si mihi probabis ea, quae dices, libenter assentiar.",
  "Probabo, inquit, modo ista sis aequitate, quam ostendis.",
  "Sed uti oratione perpetua malo quam interrogare aut interrogari.",
  "Ut placet, inquam.",
  "Tum dicere exorsus est.",
  "Primum igitur, inquit, sic agam, ut ipsi auctori huius disciplinae placet.",
  "Constituam, quid et quale sit id, de quo quaerimus, non quo ignorare vos arbitrer, sed ut ratione et via procedat oratio.",
  "Quaerimus igitur, quid sit extremum et ultimum bonorum, quod omnium philosophorum sententia tale debet esse, ut ad id omnia referri oporteat, ipsum autem nusquam.",
  "Hoc Epicurus in voluptate ponit, quod summum bonum esse vult, summumque malum dolorem, idque instituit docere sic.",
  "Omne animal, simul atque natum sit, voluptatem appetere eaque gaudere ut summo bono, dolorem aspernari ut summum malum et, quantum possit, a se repellere, idque facere nondum depravatum ipsa natura incorrupte atque integre iudicante.",
  "Itaque negat opus esse ratione neque disputatione, quam ob rem voluptas expetenda, fugiendus dolor sit.",
  "Sentiri haec putat, ut calere ignem, nivem esse albam, dulce mel.",
  "Quorum nihil oportere exquisitis rationibus confirmare, tantum satis esse admonere.",
  "Interesse enim inter argumentum conclusionemque rationis et inter mediocrem animadversionem atque admonitionem.",
  "Altera occulta quaedam et quasi involuta aperiri, altera prompta et aperta iudicari.",
  "Etenim quoniam detractis de homine sensibus reliqui nihil est, necesse est, quid aut ad naturam aut contra sit, a natura ipsa iudicari.",
  "Ea quid percipit aut quid iudicat, quo aut petat aut fugiat aliquid, praeter voluptatem et dolorem?",
  "Sunt autem quidam e nostris, qui haec subtilius velint tradere et negent satis esse, quid bonum sit aut quid malum, sensu iudicari, sed animo etiam ac ratione intellegi posse et voluptatem ipsam per se esse expetendam et dolorem ipsum per se esse fugiendum.",
  "Itaque aiunt hanc quasi naturalem atque insitam in animis nostris inesse notionem, ut alterum esse appetendum, alterum aspernandum sentiamus.",
  "Alii autem, quibus ego assentior, cum a philosophis compluribus permulta dicantur, cur nec voluptas in bonis sit numeranda nec in malis dolor, non existimant oportere nimium nos causae confidere, sed et argumentandum et accurate disserendum et rationibus conquisitis de voluptate et dolore disputandum putant.",
  "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo.",
  "Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem.",
  "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
  "Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?",
  "At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  "Et harum quidem rerum facilis est et expedita distinctio.",
  "Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae.",
  "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
];
